mkdir -p "./dist/about/"
mkdir -p "./dist/cwcms/"
mkdir -p "./dist/controllers"
SCRIPT_FILENAME=index.php REQUEST_URI=/ php index.php > "./dist/index.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/views php photo_gallery.php > "./dist/views/photo_gallery.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/views php sub_pages.php > "./dist/views/sub_pages.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/views/templates php main.tpl.php > "./dist/views/templates/main.tpl.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/views/templates php page.tpl.php > "./dist/views/templates/page.tpl.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/views/contact php contact_form.php > "./dist/views/contact/contact_form.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/cwcms php index.php > "./dist/cwcms/index.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/controllers php contact-us.php > "./dist/controllers/contact-us.html"