mkdir -p "./dist/about/"
mkdir -p "./dist/cwcms/"
mkdir -p "./dist/controllers"
SCRIPT_FILENAME=index.php REQUEST_URI=/ php index.php > "./dist/index.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/cwcms php index.php > "./dist/cwcms/index.html"
SCRIPT_FILENAME=index.php REQUEST_URI=/controllers php contact-us.php > "./dist/controllers/contact-us.html"